2017/08/28 15:54:50 [emerg] 31066#0: open() "./mime.types" failed (2: No such file or directory) in ./nginx.conf:18
2017/08/28 15:56:16 [emerg] 31160#0: bind() to 0.0.0.0:80 failed (13: Permission denied)
2017/08/28 15:56:29 [emerg] 31177#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2017/08/28 15:56:29 [emerg] 31177#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2017/08/28 15:56:29 [emerg] 31177#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2017/08/28 15:56:29 [emerg] 31177#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2017/08/28 15:56:29 [emerg] 31177#0: bind() to 0.0.0.0:8080 failed (48: Address already in use)
2017/08/28 15:57:16 [error] 31228#0: *1 "./html/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8888"
2017/08/28 15:58:35 [error] 31228#0: *2 "./html/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8888"
2017/08/28 16:05:58 [error] 31757#0: *1 "./html/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8888"
2017/08/28 16:05:58 [error] 31757#0: *1 open() "./html/favicon.ico" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/"
2017/08/28 16:06:33 [error] 31757#0: *1 "./html/index.html" is not found (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8888"
2017/08/28 16:06:39 [error] 31757#0: *2 open() "./html/index.html" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /index.html HTTP/1.1", host: "localhost:8888"
2017/08/28 16:17:23 [error] 32535#0: *2 open() "/Users/alexajax/Desktop/GoToCC/frontend/gtc/favicon.ico" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET /favicon.ico HTTP/1.1", host: "localhost:8888", referrer: "http://localhost:8888/"
2017/09/02 20:15:36 [error] 73781#0: *4 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "http://[::1]:1488/", host: "localhost:8888"
2017/09/02 20:15:53 [error] 73781#0: *1 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST / HTTP/1.1", upstream: "http://[::1]:1488/", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/02 20:28:36 [emerg] 77726#0: open() "/var/log/nginx/access_log" failed (2: No such file or directory)
2017/09/02 20:36:30 [error] 77804#0: *4 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST / HTTP/1.1", upstream: "http://[::1]:1488/", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/03 16:48:25 [error] 27724#0: *4 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST / HTTP/1.1", upstream: "http://[::1]:1488/", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/03 17:08:15 [error] 27724#0: *11 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "HEAD /api/explorer/v1/blocks/3 HTTP/1.1", upstream: "http://[::1]:1488/api/explorer/v1/blocks/3", host: "127.0.0.1:8888"
2017/09/03 17:10:39 [error] 27724#0: *18 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "HEAD /api/explorer/v1/blocks/3 HTTP/1.1", upstream: "http://[::1]:1488/api/explorer/v1/blocks/3", host: "127.0.0.1:8888"
2017/09/03 17:35:18 [error] 27724#0: *27 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/03 19:32:56 [error] 36062#0: *3 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/03 19:37:38 [error] 36169#0: *4 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "127.0.0.1:8888"
2017/09/03 19:44:06 [error] 36169#0: *12 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/03 19:53:42 [error] 36169#0: *16 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/03 19:57:14 [error] 36169#0: *29 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "127.0.0.1:8888"
2017/09/03 20:03:49 [error] 36169#0: *37 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/03 20:05:58 [error] 36169#0: *47 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
2017/09/03 20:07:25 [error] 36169#0: *47 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "POST /api/services/cryptocurrency/v1/wallets/transaction HTTP/1.1", upstream: "http://[::1]:1488/api/services/cryptocurrency/v1/wallets/transaction", host: "localhost:8888", referrer: "http://localhost:8000/admin.html"
